plugins {
    id 'com.android.application'
}

android {
    namespace 'com.calclensth.app'
    compileSdk 36

    defaultConfig {
        applicationId 'com.calclensth.app'
        minSdk 24
        targetSdk 35
        versionCode 6
        versionName '0.3.2'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

configurations.configureEach {
    resolutionStrategy {
        force 'org.jetbrains.kotlin:kotlin-stdlib:1.8.22'
        force 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.8.22'
        force 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.22'
    }
}

dependencies {
    implementation 'androidx.core:core:1.15.0'
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'com.google.mlkit:text-recognition:16.0.1'
    implementation 'com.github.yalantis:ucrop:2.2.11'
}
